blank_issues_enabled: false
contact_links:
  - name: Security Vulnerability
    url: https://github.com/vakesz/notification_app/security/policy
    about: Please report security vulnerabilities privately via our security policy
  - name: General Questions
    url: https://github.com/vakesz/notification_app/discussions
    about: Ask questions and discuss ideas in GitHub Discussions
