name: Release Docker Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag (e.g. 1.2.3)'
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    if: ${{ github.actor == 'vakesz' }}

    steps:
      - name: Greet the runner
        run: echo "👋 Hello ${{ github.actor }}!"

      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up QEMU (for multi-arch)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.REGISTRY_USERNAME }}/notification_app:${{ github.event.inputs.tag }}
            ${{ secrets.REGISTRY_USERNAME }}/notification_app:latest
