name: Release Docker Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag (e.g. 1.2.3)'
        required: true

# Grant the GITHUB_TOKEN rights to push packages
permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'vakesz' }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU (for multi-arch)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/notification_app:${{ github.event.inputs.tag }}
            ghcr.io/${{ github.repository_owner }}/notification_app:latest
