name: Deploy README as HTML to Pages

on:
  push:
    branches: ["main"]
    paths:
      - "README.md"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Create HTML template
        run: |
          cat > template.html << 'EOF'
          <!DOCTYPE html>
          <html lang="$lang$">
          <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <!-- Prevent flash-of-unstyled light background -->
            <meta name="color-scheme" content="light dark">
            <title>$title$</title>

            <!-- Combined GitHub Markdown CSS for auto light/dark -->
            <link rel="stylesheet"
                  href="https://cdn.jsdelivr.net/npm/github-markdown-css@5.4.0/github-markdown.css">

            <!-- Highlight.js styles -->
            <link rel="stylesheet"
                  href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/styles/github.min.css"
                  media="(prefers-color-scheme: light)">
            <link rel="stylesheet"
                  href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/styles/github-dark.min.css"
                  media="(prefers-color-scheme: dark)">

            <style>
              body {
                box-sizing: border-box;
                min-width: 200px;
                max-width: 980px;
                margin: 0 auto;
                padding: 45px;
              }
              .markdown-body {
                border-radius: 6px;
                padding: 32px;
                box-shadow: 0 1px 3px rgba(0,0,0,0.12),
                            0 1px 2px rgba(0,0,0,0.24);
              }
            </style>
          </head>
          <body>
            <article class="markdown-body">
              $body$
            </article>
            <!-- Highlight.js runtime -->
            <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/highlight.min.js"></script>
            <script>hljs.highlightAll();</script>
          </body>
          </html>
          EOF

      - name: Generate HTML from README.md (no alt-text, with syntax highlight)
        run: |
          pandoc README.md \
            --standalone \
            --metadata title="Notification App – Project Documentation" \
            --metadata author="Notification App" \
            --metadata lang="en" \
            --template template.html \
            -o index.html

          # strip out all alt="…" attributes
          sed -i 's/ alt="[^"]*"//g' index.html

      - name: Prepare Pages directory
        run: |
          mkdir -p public
          mv index.html public/

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
