# Simple workflow for converting README.md to HTML and deploying to GitHub Pages
name: Deploy README as HTML to Pages

on:
  push:
    branches: ["main"]
    paths:
      - "README.md"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Generate HTML from README.md
        run: |
          pandoc README.md \
            --standalone \
            --metadata title="Notification App - Project Documentation" \
            --metadata author="Notification App" \
            --metadata lang="en" \
            --css https://cdn.jsdelivr.net/npm/github-markdown-css@5.4.0/github-markdown-light.css \
            --highlight-style github \
            --template <(echo '<!DOCTYPE html>
          <html lang="$lang$">
          <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>$title$</title>
            <link rel="stylesheet" href="$css$">
            <style>
              body {
                box-sizing: border-box;
                min-width: 200px;
                max-width: 980px;
                margin: 0 auto;
                padding: 45px;
                background-color: #f6f8fa;
              }
              .markdown-body {
                background-color: white;
                border-radius: 6px;
                padding: 32px;
                box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24);
              }
              h1 { color: #0969da; border-bottom: 2px solid #0969da; }
              h2 { color: #656d76; }
              code { background-color: #f6f8fa; padding: 2px 4px; border-radius: 3px; }
              pre { background-color: #f6f8fa; border-radius: 6px; }
            </style>
          </head>
          <body>
            <article class="markdown-body">
              $body$
            </article>
          </body>
          </html>') \
            -o index.html

      - name: Prepare Pages directory
        run: |
          mkdir -p public
          mv index.html public/

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Must be a directory, not a file
          path: public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
